on: [push, pull_request]
name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build & Test
        run: make build test
